spring.application.name=hrms
# =========================
# = DATABASE CONFIGURATION
# =========================
spring.datasource.url=jdbc:mysql://localhost:3306/hrms
spring.datasource.username=root
spring.datasource.password=Sai@12345
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA & Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

# =========================
# = JWT CONFIGURATION
# =========================
jwt.secret=S3cr3tKey@1234567890$!fjoeirjfowjFODS83jfods8d7g8dfH23##@!kjhsdfKJSDF
jwt.expiration=3600000

# =========================
# = SPRING SERVER SETTINGS
# =========================
server.port=8080
spring.main.allow-bean-definition-overriding=true
